# Generated by Django 4.2.23 on 2025-07-26 20:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailing_automations_actions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('condition_name', models.CharField(max_length=100)),
                ('condition_type', models.CharField(choices=[('field_value', 'Field Value'), ('list_membership', 'List Membership'), ('tag_presence', 'Tag Presence'), ('email_engagement', 'Email Engagement'), ('date_comparison', 'Date Comparison'), ('custom_field', 'Custom Field')], max_length=30)),
                ('operator', models.CharField(choices=[('equals', 'Equals'), ('not_equals', 'Not Equals'), ('contains', 'Contains'), ('not_contains', 'Not Contains'), ('greater_than', 'Greater Than'), ('less_than', 'Less Than'), ('exists', 'Exists'), ('not_exists', 'Not Exists')], max_length=20)),
                ('field_name', models.CharField(max_length=100)),
                ('comparison_value', models.CharField(blank=True, max_length=255)),
                ('logical_operator', models.CharField(default='AND', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('evaluation_count', models.IntegerField(default=0)),
                ('true_count', models.IntegerField(default=0)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing_automations_actions.automationaction')),
            ],
        ),
    ]
