# Generated by Django 4.2.23 on 2025-07-26 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailing_automations_conditions', '0001_initial'),
        ('mailing_automations_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationcondition',
            name='automation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='mailing_automations_core.automation'),
        ),
    ]
