# Generated by Django 4.2.23 on 2025-07-26 20:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailing_contacts_core', '0001_initial'),
        ('brands_core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormIntegration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('form_type', models.CharField(choices=[('subscription', 'Subscription'), ('lead_generation', 'Lead Generation'), ('contact', 'Contact'), ('newsletter', 'Newsletter'), ('download', 'Download'), ('webinar', 'Webinar'), ('custom', 'Custom')], max_length=30)),
                ('double_optin_required', models.BooleanField(default=True)),
                ('redirect_url', models.URLField(blank=True)),
                ('success_message', models.TextField(blank=True)),
                ('field_mapping', models.JSONField(default=dict)),
                ('custom_fields', models.JSONField(default=list)),
                ('embed_code', models.TextField(blank=True)),
                ('submissions_count', models.IntegerField(default=0)),
                ('conversion_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands_core.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('form_data', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('processed', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='mailing_integrations_forms.formintegration')),
                ('subscriber_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing_contacts_core.emailsubscriber')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
