<?php

function init_auto_blogger_feature() {
    // Récupère les options du plugin pour Auto Blogger
    $options = get_option('mega_hub_options_auto_blogger');

    // Vérifie si l'option 'mega_hub_auto_blogger_enable' est définie et différente de 'on'
    if (!isset($options['mega_hub_auto_blogger_enable']) || $options['mega_hub_auto_blogger_enable'] !== 'on') {
        return; // Sort de la fonction si Auto Blogger n'est pas activé
    }


    function handle_ab_form_submission() {
        check_ajax_referer('mega-hub-auto-blogger-form', 'security');
    
        // Récupère les données du formulaire
        // Assure-toi de valider et nettoyer toutes les entrées pour la sécurité
        $titles = explode("\n", sanitize_textarea_field($_POST['titles']));
        $model_selection = sanitize_text_field($_POST['model_selection']);
        // Ajoute ici la récupération des autres champs du formulaire si nécessaire
    
        // Définis les coûts par article pour chaque modèle
        $costs_per_article = [
            'gpt-4-0125-preview' => 0.20,
            'gpt-4-1106-preview' => 0.15,
            'gpt-3.5-turbo-0125' => 0.01,
            'gpt-4' => 0.40,
            'gemini-1.0' => 0.25,
        ];
    
        $cost_per_article = isset($costs_per_article[$model_selection]) ? $costs_per_article[$model_selection] : 0.20; // Utilise un coût par défaut si nécessaire
    
        // Calcule le coût total en fonction du nombre d'articles et du coût par article
        $number_of_articles = count(array_filter($titles, 'trim')); // Ne compte que les lignes non vides
        $total_cost = $number_of_articles * $cost_per_article;
    
        // Ici, tu peux appeler ta fonction pour traiter la demande, par exemple :
        // send_autoblog_request_to_megahub($titles, $model_selection, ...);
    
        wp_send_json_success(array('message' => __('Your request has been processed. You will be notified once the articles are ready.', 'mega-hub')));
    }
    add_action('wp_ajax_handle_ab_form_submission', 'handle_ab_form_submission');
    



function register_custom_api_endpoint() {
    register_rest_route('megahub/v1', '/megahub-publish', array(
        'methods' => 'POST',
        'callback' => 'handle_api_response_publish_articles',
        'permission_callback' => '__return_true',
    ));
}

add_action('rest_api_init', 'register_custom_api_endpoint');

function handle_api_response_publish_articles($request) {
    $options = get_option('mega_hub_options');
    
    // Vérifie si les notifications par e-mail sont activées
    if (isset($options['mega_hub_email_notifications']) && $options['mega_hub_email_notifications']) {
        $user_email = !empty($options['mega_hub_email']) ? $options['mega_hub_email'] : get_option('admin_email');

        $subject = __('Your articles are ready!', 'mega-hub');
        $message = __('Hello! Your articles generated by Mega Hub Auto Blogger are now ready. Please check your dashboard to review them.', 'mega-hub');
        $headers = array('Content-Type: text/html; charset=UTF-8');

        wp_mail($user_email, $subject, $message, $headers);
    }

    return new WP_REST_Response(array('message' => 'Articles processed.'), 200);
}



} // fermeture du init
add_action('init', 'init_auto_blogger_feature');



/* ----------------- A partir d'ici ça charge même si la fonctionnalité est désactivée ----------------------- */