# Generated by Django 4.2.23 on 2025-07-22 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm_entities_core', '0001_initial'),
        ('brands_core', '0002_initial'),
        ('crm_pipeline_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company_categorization_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='pipeline',
            field=models.ForeignKey(help_text='Pipeline commercial', on_delete=django.db.models.deletion.CASCADE, to='crm_pipeline_core.pipeline'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='primary_contact',
            field=models.ForeignKey(blank=True, help_text='Contact principal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_opportunities', to='crm_entities_core.contact'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='stage',
            field=models.ForeignKey(help_text='Étape actuelle', on_delete=django.db.models.deletion.CASCADE, to='crm_pipeline_core.stage'),
        ),
        migrations.AddField(
            model_name='contact',
            name='account',
            field=models.ForeignKey(help_text='Compte associé', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm_entities_core.account'),
        ),
        migrations.AddField(
            model_name='contact',
            name='brand',
            field=models.ForeignKey(help_text='Brand gestionnaire de cette entité', on_delete=django.db.models.deletion.CASCADE, to='brands_core.brand'),
        ),
        migrations.AddField(
            model_name='contact',
            name='owner',
            field=models.ForeignKey(help_text='Propriétaire/responsable de cette entité', on_delete=django.db.models.deletion.CASCADE, related_name='owned_%(class)s_entities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='brand',
            field=models.ForeignKey(help_text='Brand gestionnaire de cette entité', on_delete=django.db.models.deletion.CASCADE, to='brands_core.brand'),
        ),
        migrations.AddField(
            model_name='account',
            name='company_category',
            field=models.ForeignKey(blank=True, help_text='Catégorie structurée', null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_categorization_core.industrycategory'),
        ),
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(help_text='Propriétaire/responsable de cette entité', on_delete=django.db.models.deletion.CASCADE, related_name='owned_%(class)s_entities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='parent_account',
            field=models.ForeignKey(blank=True, help_text='Compte parent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_accounts', to='crm_entities_core.account'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['brand', 'stage'], name='crm_opportu_brand_i_5cf67a_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['account'], name='crm_opportu_account_505f90_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['opportunity_number'], name='crm_opportu_opportu_682685_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['close_date'], name='crm_opportu_close_d_9211cb_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['amount'], name='crm_opportu_amount_5e8d75_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['probability'], name='crm_opportu_probabi_6b7163_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['is_closed', 'is_won'], name='crm_opportu_is_clos_f9aa35_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['brand', 'account'], name='crm_contact_brand_i_0c5b16_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['email'], name='crm_contact_email_240305_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['last_name', 'first_name'], name='crm_contact_last_na_cda0e5_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['is_primary_contact'], name='crm_contact_is_prim_7a196e_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['lead_score'], name='crm_contact_lead_sc_82bee6_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['is_decision_maker'], name='crm_contact_is_deci_fad50e_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['brand', 'account_type'], name='crm_account_brand_i_1a7ca1_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['name'], name='crm_account_name_c7a3b4_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_number'], name='crm_account_account_9ed356_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['customer_priority'], name='crm_account_custome_44fa45_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['health_score'], name='crm_account_health__b6a101_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['parent_account'], name='crm_account_parent__272a8b_idx'),
        ),
    ]
