# Generated by Django 4.2.23 on 2025-07-26 20:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands_core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=255)),
                ('brand_logo', models.ImageField(blank=True, null=True, upload_to='branding/logos/')),
                ('primary_color', models.CharField(default='#000000', max_length=7)),
                ('secondary_color', models.CharField(default='#ffffff', max_length=7)),
                ('font_family', models.CharField(default='Arial', max_length=100)),
                ('email_footer', models.TextField(blank=True)),
                ('social_links', models.JSONField(default=dict)),
                ('default_css', models.TextField(blank=True)),
                ('header_template', models.TextField(blank=True)),
                ('footer_template', models.TextField(blank=True)),
                ('unsubscribe_page_url', models.URLField(blank=True)),
                ('preference_center_url', models.URLField(blank=True)),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='brands_core.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
