# Generated by Django 4.2.23 on 2025-07-26 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brands_core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('newsletter', 'Newsletter'), ('promotional', 'Promotional'), ('transactional', 'Transactional'), ('welcome', 'Welcome'), ('reengagement', 'Re-engagement'), ('abandoned_cart', 'Abandoned Cart'), ('event', 'Event'), ('announcement', 'Announcement')], default='newsletter', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('html_content', models.TextField()),
                ('text_content', models.TextField(blank=True)),
                ('design_config', models.JSONField(default=dict)),
                ('variables', models.JSONField(default=list)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='templates/previews/')),
                ('is_favorite', models.BooleanField(default=False)),
                ('usage_count', models.IntegerField(default=0)),
                ('tags', models.JSONField(default=list)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands_core.brand')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['category', 'brand'], name='mailing_tem_categor_053ecd_idx'), models.Index(fields=['status'], name='mailing_tem_status_2494a3_idx')],
                'unique_together': {('name', 'brand')},
            },
        ),
    ]
