# Generated by Django 4.2.23 on 2025-07-26 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brands_core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('manager', 'Manager'), ('admin', 'Admin')], default='viewer', max_length=30)),
                ('can_create_campaigns', models.BooleanField(default=False)),
                ('can_edit_campaigns', models.BooleanField(default=False)),
                ('can_send_campaigns', models.BooleanField(default=False)),
                ('can_manage_lists', models.BooleanField(default=False)),
                ('can_manage_templates', models.BooleanField(default=False)),
                ('can_view_analytics', models.BooleanField(default=True)),
                ('can_export_data', models.BooleanField(default=False)),
                ('can_manage_integrations', models.BooleanField(default=False)),
                ('can_manage_settings', models.BooleanField(default=False)),
                ('send_limit_per_day', models.IntegerField(blank=True, null=True)),
                ('allowed_features', models.JSONField(default=list)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands_core.brand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'brand')},
            },
        ),
    ]
