# Generated by Django 4.2.23 on 2025-07-26 20:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationAction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_name', models.CharField(max_length=100)),
                ('action_type', models.CharField(choices=[('send_email', 'Send Email'), ('add_to_list', 'Add to List'), ('remove_from_list', 'Remove from List'), ('add_tag', 'Add Tag'), ('remove_tag', 'Remove Tag'), ('update_field', 'Update Field'), ('wait', 'Wait'), ('webhook', 'Webhook'), ('api_call', 'API Call'), ('conditional_split', 'Conditional Split')], max_length=30)),
                ('action_order', models.IntegerField(default=0)),
                ('action_config', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('execution_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('failure_count', models.IntegerField(default=0)),
                ('last_executed', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['action_order'],
            },
        ),
    ]
