# Generated by Django 4.2.23 on 2025-07-26 20:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brands_core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('automation_type', models.CharField(choices=[('drip', 'Drip Campaign'), ('welcome', 'Welcome Series'), ('abandoned_cart', 'Abandoned Cart'), ('reengagement', 'Re-engagement'), ('birthday', 'Birthday Campaign'), ('anniversary', 'Anniversary'), ('educational', 'Educational Series'), ('nurturing', 'Lead Nurturing'), ('onboarding', 'User Onboarding'), ('post_purchase', 'Post Purchase'), ('custom', 'Custom Workflow')], default='drip', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('entry_criteria', models.JSONField()),
                ('exit_criteria', models.JSONField(default=dict)),
                ('allow_re_entry', models.BooleanField(default=False)),
                ('re_entry_delay_days', models.IntegerField(default=0)),
                ('total_entries', models.IntegerField(default=0)),
                ('active_subscribers', models.IntegerField(default=0)),
                ('completed_subscribers', models.IntegerField(default=0)),
                ('conversion_goal', models.CharField(blank=True, max_length=100)),
                ('conversion_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands_core.brand')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'brand')},
            },
        ),
    ]
