# Generated by Django 4.2.23 on 2025-07-26 20:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailing_deliverability_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverabilityMonitoring',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monitoring_date', models.DateField()),
                ('inbox_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('spam_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('missing_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('avg_delivery_time_minutes', models.IntegerField(default=0)),
                ('gmail_inbox_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('outlook_inbox_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('yahoo_inbox_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('provider_feedback', models.JSONField(default=dict)),
                ('recommendations', models.TextField(blank=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring', to='mailing_deliverability_core.deliverabilityconfig')),
            ],
            options={
                'unique_together': {('config', 'monitoring_date')},
            },
        ),
    ]
