# Generated by Django 4.2.23 on 2025-07-21 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_core', '0003_company_trial_expires_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaasCompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('additional_info', models.JSONField(blank=True, default=dict, help_text='Informations additionnelles spécifiques au secteur')),
                ('industry_score', models.IntegerField(blank=True, help_text="Score d'adéquation avec le secteur (0-100)", null=True)),
                ('is_validated', models.BooleanField(default=False, help_text='Profil validé par un expert secteur')),
                ('validated_at', models.DateTimeField(blank=True, help_text='Date de validation', null=True)),
                ('vertical', models.CharField(choices=[('crm', 'CRM & Sales'), ('marketing', 'Marketing Automation'), ('hr', 'RH & Talents'), ('accounting', 'Comptabilité & Finance'), ('project_mgmt', 'Gestion de Projets'), ('communication', 'Communication & Collaboration'), ('analytics', 'Analytics & BI'), ('ecommerce', 'E-commerce & Retail'), ('education', 'EdTech & Formation'), ('vertical_saas', 'SaaS Vertical Spécialisé')], help_text='Vertical SaaS principal', max_length=20)),
                ('target_market', models.CharField(choices=[('b2b', 'B2B'), ('b2c', 'B2C'), ('b2b2c', 'B2B2C'), ('marketplace', 'Marketplace')], default='b2b', help_text='Marché cible', max_length=15)),
                ('pricing_model', models.CharField(default='subscription', help_text='Modèle de pricing (subscription, usage-based, freemium)', max_length=50)),
                ('has_free_tier', models.BooleanField(default=False, help_text="Dispose d'une offre gratuite")),
                ('has_enterprise_tier', models.BooleanField(default=False, help_text="Dispose d'une offre Enterprise")),
                ('mrr_estimate', models.DecimalField(blank=True, decimal_places=2, help_text='MRR estimé (€)', max_digits=12, null=True)),
                ('arr_estimate', models.DecimalField(blank=True, decimal_places=2, help_text='ARR estimé (€)', max_digits=12, null=True)),
                ('customer_count', models.IntegerField(blank=True, help_text='Nombre de clients', null=True)),
                ('churn_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Taux de churn mensuel (%)', max_digits=5, null=True)),
                ('primary_tech_stack', models.CharField(blank=True, help_text='Stack technique principal (ex: React/Node.js, Django/Python)', max_length=100)),
                ('hosting_provider', models.CharField(blank=True, help_text="Fournisseur d'hébergement (AWS, GCP, Azure)", max_length=50)),
                ('api_integrations_count', models.IntegerField(blank=True, help_text="Nombre d'intégrations API disponibles", null=True)),
                ('has_public_api', models.BooleanField(default=False, help_text="Dispose d'une API publique")),
                ('company', models.OneToOneField(help_text='Entreprise associée à ce profil', on_delete=django.db.models.deletion.CASCADE, to='company_core.company')),
                ('validated_by', models.ForeignKey(blank=True, help_text='Expert qui a validé le profil', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil SaaS',
                'verbose_name_plural': 'Profils SaaS',
                'db_table': 'saas_company_profile',
                'indexes': [models.Index(fields=['vertical'], name='saas_compan_vertica_3c1f55_idx'), models.Index(fields=['target_market'], name='saas_compan_target__44e2e9_idx'), models.Index(fields=['has_enterprise_tier'], name='saas_compan_has_ent_36102d_idx')],
            },
        ),
    ]
