# Generated by Django 4.2.23 on 2025-07-26 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing_lists_core', '0001_initial'),
        ('brands_core', '0002_initial'),
        ('mailing_campaigns_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignlist',
            name='mailing_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing_lists_core.mailinglist'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands_core.brand'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_lists',
            field=models.ManyToManyField(blank=True, through='mailing_campaigns_core.CampaignList', to='mailing_lists_core.mailinglist'),
        ),
    ]
