# Generated by Django 4.2.23 on 2025-07-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailing_lists_segments', '0001_initial'),
        ('mailing_campaigns_core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='target_segments',
            field=models.ManyToManyField(blank=True, to='mailing_lists_segments.listsegment'),
        ),
    ]
