# Generated by Django 4.2.23 on 2025-07-26 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailing_campaigns_core', '0003_initial'),
        ('mailing_templates_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing_templates_core.emailtemplate'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'brand'], name='mailing_cam_status_553609_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['campaign_type'], name='mailing_cam_campaig_190050_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['sent_at'], name='mailing_cam_sent_at_e6a250_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaign',
            unique_together={('name', 'brand')},
        ),
    ]
