# Generated by Django 4.2.23 on 2025-07-26 20:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailing_configuration_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendingLimits',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hourly_limit', models.IntegerField(default=1000)),
                ('daily_limit', models.IntegerField(default=10000)),
                ('monthly_limit', models.IntegerField(default=100000)),
                ('current_hour_sent', models.IntegerField(default=0)),
                ('current_day_sent', models.IntegerField(default=0)),
                ('current_month_sent', models.IntegerField(default=0)),
                ('hour_reset_time', models.DateTimeField(blank=True, null=True)),
                ('day_reset_time', models.DateTimeField(blank=True, null=True)),
                ('month_reset_time', models.DateTimeField(blank=True, null=True)),
                ('send_rate_per_minute', models.IntegerField(default=100)),
                ('burst_limit', models.IntegerField(default=500)),
                ('alert_threshold_percent', models.IntegerField(default=80)),
                ('last_alert_sent', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mailing_configuration_core.mailingaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
