# Generated by Django 4.2.23 on 2025-07-26 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brands_core', '0002_initial'),
        ('mailing_campaigns_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuppressionList',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('suppression_type', models.CharField(choices=[('unsubscribe', 'Unsubscribe'), ('bounce', 'Bounce'), ('complaint', 'Complaint'), ('manual', 'Manual'), ('global', 'Global')], max_length=30)),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('is_global', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brands_core.brand')),
                ('source_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing_campaigns_core.campaign')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
