# Generated by Django 4.2.23 on 2025-07-26 20:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands_core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('trial', 'Trial'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('plan_type', models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise'), ('custom', 'Custom')], default='starter', max_length=30)),
                ('monthly_send_limit', models.IntegerField(default=10000)),
                ('current_month_sent', models.IntegerField(default=0)),
                ('subscriber_limit', models.IntegerField(default=2000)),
                ('current_subscribers', models.IntegerField(default=0)),
                ('features_enabled', models.JSONField(default=dict)),
                ('timezone', models.CharField(default='Europe/Paris', max_length=50)),
                ('default_from_name', models.CharField(blank=True, max_length=100)),
                ('default_from_email', models.EmailField(blank=True, max_length=254)),
                ('default_reply_to', models.EmailField(blank=True, max_length=254)),
                ('compliance_settings', models.JSONField(default=dict)),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='brands_core.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
