# Generated by Django 4.2.23 on 2025-07-26 20:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailing_contacts_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberTracking',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_emails_sent', models.IntegerField(default=0)),
                ('total_emails_opened', models.IntegerField(default=0)),
                ('total_emails_clicked', models.IntegerField(default=0)),
                ('total_emails_bounced', models.IntegerField(default=0)),
                ('total_emails_unsubscribed', models.IntegerField(default=0)),
                ('engagement_score', models.DecimalField(decimal_places=4, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('last_email_sent', models.DateTimeField(blank=True, null=True)),
                ('last_email_opened', models.DateTimeField(blank=True, null=True)),
                ('last_email_clicked', models.DateTimeField(blank=True, null=True)),
                ('last_activity_date', models.DateTimeField(blank=True, null=True)),
                ('days_since_last_activity', models.IntegerField(default=0)),
                ('is_engaged', models.BooleanField(default=True)),
                ('segment_tags', models.JSONField(default=list)),
                ('subscriber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mailing_contacts_core.emailsubscriber')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
