# Generated by Django 4.2.23 on 2025-07-26 20:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DNSRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=255)),
                ('record_type', models.CharField(choices=[('SPF', 'SPF'), ('DKIM', 'DKIM'), ('DMARC', 'DMARC'), ('MX', 'MX'), ('A', 'A'), ('CNAME', 'CNAME'), ('TXT', 'TXT')], max_length=10)),
                ('value', models.TextField()),
                ('ttl', models.IntegerField(default=3600)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailAuthentication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('spf_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('spf_record', models.TextField(blank=True)),
                ('spf_last_check', models.DateTimeField(blank=True, null=True)),
                ('dkim_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('dkim_selector', models.CharField(blank=True, max_length=50)),
                ('dkim_public_key', models.TextField(blank=True)),
                ('dkim_last_check', models.DateTimeField(blank=True, null=True)),
                ('dmarc_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('dmarc_record', models.TextField(blank=True)),
                ('dmarc_last_check', models.DateTimeField(blank=True, null=True)),
                ('authentication_score', models.IntegerField(default=0)),
                ('last_validation', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
