# Generated by Django 4.2.23 on 2025-07-26 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailing_deliverability_core', '0001_initial'),
        ('mailing_deliverability_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailauthentication',
            name='config',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mailing_deliverability_core.deliverabilityconfig'),
        ),
        migrations.AddField(
            model_name='dnsrecord',
            name='authentication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dns_records', to='mailing_deliverability_authentication.emailauthentication'),
        ),
    ]
