# Generated by Django 4.2.23 on 2025-07-22 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm_entities_core', '0001_initial'),
        ('brands_core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRole',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_type', models.CharField(choices=[('decision_maker', 'Décideur'), ('influencer', 'Influenceur'), ('user', 'Utilisateur'), ('technical_buyer', 'Acheteur Technique'), ('economic_buyer', 'Acheteur Économique'), ('coach', 'Coach'), ('gatekeeper', 'Gatekeeper'), ('sponsor', 'Sponsor')], help_text='Type de rôle', max_length=20)),
                ('involvement_level', models.CharField(choices=[('primary', 'Principal'), ('secondary', 'Secondaire'), ('observer', 'Observateur'), ('supporter', 'Supporter')], default='primary', help_text="Niveau d'implication", max_length=15)),
                ('influence_score', models.IntegerField(default=50, help_text="Score d'influence (0-100)")),
                ('decision_power', models.IntegerField(default=50, help_text='Pouvoir de décision (0-100)')),
                ('is_active', models.BooleanField(default=True, help_text='Rôle actif')),
                ('start_date', models.DateField(auto_now_add=True, help_text='Date début du rôle')),
                ('end_date', models.DateField(blank=True, help_text='Date fin du rôle', null=True)),
                ('description', models.TextField(blank=True, help_text='Description du rôle')),
                ('account', models.ForeignKey(blank=True, help_text='Compte (si rôle au niveau compte)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_roles', to='crm_entities_core.account')),
                ('brand', models.ForeignKey(help_text='Brand gestionnaire de cette entité', on_delete=django.db.models.deletion.CASCADE, to='brands_core.brand')),
                ('contact', models.ForeignKey(help_text='Contact concerné', on_delete=django.db.models.deletion.CASCADE, related_name='contact_roles', to='crm_entities_core.contact')),
                ('opportunity', models.ForeignKey(blank=True, help_text='Opportunité (si rôle spécifique à une affaire)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_roles', to='crm_entities_core.opportunity')),
                ('owner', models.ForeignKey(help_text='Propriétaire/responsable de cette entité', on_delete=django.db.models.deletion.CASCADE, related_name='owned_%(class)s_entities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rôle Contact',
                'verbose_name_plural': 'Rôles Contacts',
                'db_table': 'crm_contact_role',
                'ordering': ['-influence_score', '-decision_power'],
                'indexes': [models.Index(fields=['contact', 'role_type'], name='crm_contact_contact_2d909e_idx'), models.Index(fields=['account', 'is_active'], name='crm_contact_account_de1174_idx'), models.Index(fields=['opportunity', 'is_active'], name='crm_contact_opportu_95fd6e_idx')],
                'unique_together': {('contact', 'opportunity', 'role_type'), ('contact', 'account', 'role_type')},
            },
        ),
        migrations.CreateModel(
            name='ContactRelationship',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('colleague', 'Collègue'), ('manager', 'Manager'), ('subordinate', 'Subordonné'), ('peer', 'Pair'), ('mentor', 'Mentor'), ('mentee', 'Mentoré'), ('business_partner', 'Partenaire Business'), ('referrer', 'Référent'), ('friend', 'Ami'), ('family', 'Famille')], help_text='Type de relation', max_length=20)),
                ('strength', models.IntegerField(default=50, help_text='Force de la relation (0-100)')),
                ('is_mutual', models.BooleanField(default=False, help_text='Relation mutuelle')),
                ('is_active', models.BooleanField(default=True, help_text='Relation active')),
                ('description', models.TextField(blank=True, help_text='Description de la relation')),
                ('last_interaction', models.DateField(blank=True, help_text='Dernière interaction connue', null=True)),
                ('brand', models.ForeignKey(help_text='Brand gestionnaire de cette entité', on_delete=django.db.models.deletion.CASCADE, to='brands_core.brand')),
                ('from_contact', models.ForeignKey(help_text='Contact source', on_delete=django.db.models.deletion.CASCADE, related_name='outbound_relationships', to='crm_entities_core.contact')),
                ('owner', models.ForeignKey(help_text='Propriétaire/responsable de cette entité', on_delete=django.db.models.deletion.CASCADE, related_name='owned_%(class)s_entities', to=settings.AUTH_USER_MODEL)),
                ('to_contact', models.ForeignKey(help_text='Contact cible', on_delete=django.db.models.deletion.CASCADE, related_name='inbound_relationships', to='crm_entities_core.contact')),
            ],
            options={
                'verbose_name': 'Relation Contact',
                'verbose_name_plural': 'Relations Contacts',
                'db_table': 'crm_contact_relationship',
                'ordering': ['-strength'],
                'indexes': [models.Index(fields=['from_contact', 'is_active'], name='crm_contact_from_co_67b31e_idx'), models.Index(fields=['to_contact', 'is_active'], name='crm_contact_to_cont_6b37ff_idx'), models.Index(fields=['relationship_type'], name='crm_contact_relatio_6d2197_idx')],
                'unique_together': {('from_contact', 'to_contact', 'relationship_type')},
            },
        ),
        migrations.CreateModel(
            name='AccountHierarchy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('parent_child', 'Parent-Enfant'), ('subsidiary', 'Filiale'), ('partner', 'Partenaire'), ('vendor', 'Fournisseur'), ('customer', 'Client'), ('competitor', 'Concurrent'), ('alliance', 'Alliance')], help_text='Type de relation', max_length=20)),
                ('ownership_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Pourcentage de participation', max_digits=5, null=True)),
                ('influence_level', models.IntegerField(default=50, help_text="Niveau d'influence (0-100)")),
                ('is_active', models.BooleanField(default=True, help_text='Relation active')),
                ('start_date', models.DateField(auto_now_add=True, help_text='Date début relation')),
                ('end_date', models.DateField(blank=True, help_text='Date fin relation', null=True)),
                ('description', models.TextField(blank=True, help_text='Description de la relation')),
                ('brand', models.ForeignKey(help_text='Brand gestionnaire de cette entité', on_delete=django.db.models.deletion.CASCADE, to='brands_core.brand')),
                ('child_account', models.ForeignKey(help_text='Compte enfant', on_delete=django.db.models.deletion.CASCADE, related_name='parent_relationships', to='crm_entities_core.account')),
                ('owner', models.ForeignKey(help_text='Propriétaire/responsable de cette entité', on_delete=django.db.models.deletion.CASCADE, related_name='owned_%(class)s_entities', to=settings.AUTH_USER_MODEL)),
                ('parent_account', models.ForeignKey(help_text='Compte parent', on_delete=django.db.models.deletion.CASCADE, related_name='child_relationships', to='crm_entities_core.account')),
            ],
            options={
                'verbose_name': 'Hiérarchie Comptes',
                'verbose_name_plural': 'Hiérarchies Comptes',
                'db_table': 'crm_account_hierarchy',
                'ordering': ['-influence_level'],
                'indexes': [models.Index(fields=['parent_account', 'is_active'], name='crm_account_parent__be1de3_idx'), models.Index(fields=['child_account', 'is_active'], name='crm_account_child_a_b4825c_idx'), models.Index(fields=['relationship_type'], name='crm_account_relatio_d2b4b8_idx')],
                'unique_together': {('parent_account', 'child_account', 'relationship_type')},
            },
        ),
    ]
