# Generated by Django 4.2.23 on 2025-07-22 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands_core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm_pipeline_automation', '0001_initial'),
        ('crm_pipeline_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerule',
            name='pipeline',
            field=models.ForeignKey(blank=True, help_text='Pipeline spécifique (null = toutes)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='crm_pipeline_core.pipeline'),
        ),
        migrations.AddField(
            model_name='pipelinerule',
            name='stage',
            field=models.ForeignKey(blank=True, help_text='Étape spécifique (null = toutes)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='crm_pipeline_core.stage'),
        ),
        migrations.AddField(
            model_name='automationtrigger',
            name='brand',
            field=models.ForeignKey(help_text='Brand gestionnaire de cette entité', on_delete=django.db.models.deletion.CASCADE, to='brands_core.brand'),
        ),
        migrations.AddField(
            model_name='automationtrigger',
            name='owner',
            field=models.ForeignKey(help_text='Propriétaire/responsable de cette entité', on_delete=django.db.models.deletion.CASCADE, related_name='owned_%(class)s_entities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='automationtrigger',
            name='rules',
            field=models.ManyToManyField(blank=True, help_text='Règles déclenchées', related_name='triggers', to='crm_pipeline_automation.pipelinerule'),
        ),
        migrations.AddIndex(
            model_name='ruleexecution',
            index=models.Index(fields=['rule', 'status'], name='crm_rule_ex_rule_id_57e6a7_idx'),
        ),
        migrations.AddIndex(
            model_name='ruleexecution',
            index=models.Index(fields=['opportunity', 'scheduled_at'], name='crm_rule_ex_opportu_34dede_idx'),
        ),
        migrations.AddIndex(
            model_name='ruleexecution',
            index=models.Index(fields=['status', 'scheduled_at'], name='crm_rule_ex_status_dcbf41_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelinerule',
            index=models.Index(fields=['pipeline', 'is_active'], name='crm_pipelin_pipelin_f84437_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelinerule',
            index=models.Index(fields=['stage', 'is_active'], name='crm_pipelin_stage_i_e82585_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelinerule',
            index=models.Index(fields=['trigger_type'], name='crm_pipelin_trigger_0d611b_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelinerule',
            index=models.Index(fields=['priority'], name='crm_pipelin_priorit_14f3cb_idx'),
        ),
        migrations.AddIndex(
            model_name='automationtrigger',
            index=models.Index(fields=['event_type', 'is_active'], name='crm_automat_event_t_89b505_idx'),
        ),
    ]
