# Generated by Django 4.2.23 on 2025-07-26 20:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands_core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverabilityConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sending_domain', models.CharField(max_length=255)),
                ('return_path_domain', models.CharField(blank=True, max_length=255)),
                ('dedicated_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('shared_ip_pool', models.CharField(blank=True, max_length=100)),
                ('dkim_enabled', models.BooleanField(default=False)),
                ('dkim_selector', models.CharField(blank=True, max_length=50)),
                ('spf_record', models.TextField(blank=True)),
                ('dmarc_policy', models.CharField(choices=[('none', 'None'), ('quarantine', 'Quarantine'), ('reject', 'Reject')], default='none', max_length=20)),
                ('reputation_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('warming_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('paused', 'Paused'), ('failed', 'Failed')], default='not_started', max_length=30)),
                ('daily_send_limit', models.IntegerField(default=10000)),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='brands_core.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
