// frontend/src/types/index.ts
export type * from './auth';
export type * from './global';

export type {
  User,
  UserType,
  AuthTokens,
  LoginFormData,
  RegisterFormData,
  AuthState,
  UseAuthOptions,
  UseUserSuspenseOptions,
} from './auth';

export type {
  ApiResponse,
  ApiError,
  AppError,
  PaginatedResponse,
  QueryOptions,
  MutationOptions,
  HttpMethod,
  ApiRequestConfig,
  LoadingState,
  AsyncState,
  RequestState,
  NotificationType,
  Notification,
  NavigationItem,
  AppConfig,
  EnvironmentInfo,
  ThemeMode,
  Theme,
  UIState,
  FieldError,
  FormError,
  ValidationResult,
  FormField,
  FormState,
  SearchResult,
  SearchResponse,
  PaginationParams,
  PaginationState,
  QueryParams,
  SortOption,
  FilterOption,
  SortState,
  FilterState,
  FileMetadata,
  UploadProgress,
  Maybe,
  Optional,
  Nullable,
  DeepPartial,
  DeepRequired,
  KeysOfType,
  Mutable,
  Brand,
  PromiseValue,
  AsyncReturnType,
  Environment,
} from './global';

export {
  isUser,
  isAuthTokens,
  isAuthError,
  isCompanyAdmin,
  isBrandAdmin,
  canAccessAnalytics,
  canAccessReports,
  USER_TYPES,
  ROLE_TYPES,
  PERMISSION_TYPES,
  getUserDisplayName,
  getUserInitials,
  getUserTypeLabel,
  getUserPermissions,
  hasPermission,
  hasAnyPermission,
  hasAllPermissions,
  validateEmail,
  validateUsername,
  validatePassword,
  isTokenExpired,
  getTokenExpiration,
} from './auth';

export {
  isApiError,
  isAppError,
  isPaginatedResponse,
  isDevelopment,
  isProduction,
  isTest,
  getEnvironment,
  HTTP_STATUS,
  DEFAULT_PAGINATION,
  DEFAULT_SORT,
  DEFAULT_QUERY_OPTIONS,
  LOADING_STATES,
  NOTIFICATION_TYPES,
  THEME_MODES,
} from './global';
