# Generated by Django 4.2.23 on 2025-07-26 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailing_contacts_core', '0001_initial'),
        ('mailing_analytics_core', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailevent',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing_contacts_core.emailsubscriber'),
        ),
        migrations.AddIndex(
            model_name='emailevent',
            index=models.Index(fields=['event_type', 'timestamp'], name='mailing_ana_event_t_1d761f_idx'),
        ),
        migrations.AddIndex(
            model_name='emailevent',
            index=models.Index(fields=['subscriber'], name='mailing_ana_subscri_5816e7_idx'),
        ),
        migrations.AddIndex(
            model_name='emailevent',
            index=models.Index(fields=['campaign'], name='mailing_ana_campaig_605134_idx'),
        ),
    ]
