# Generated by Django 4.2.23 on 2025-07-26 20:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationSequence',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_type', models.CharField(choices=[('linear', 'Linear'), ('conditional', 'Conditional'), ('parallel', 'Parallel')], default='linear', max_length=30)),
                ('total_emails', models.IntegerField(default=0)),
                ('average_duration_days', models.IntegerField(default=0)),
                ('completion_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('drop_off_analysis', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SequenceEmail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_order', models.IntegerField()),
                ('email_name', models.CharField(max_length=255)),
                ('delay_from_previous', models.IntegerField(default=1)),
                ('delay_unit', models.CharField(choices=[('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks')], default='days', max_length=20)),
                ('send_conditions', models.JSONField(default=dict)),
                ('sent_count', models.IntegerField(default=0)),
                ('open_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('click_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='mailing_automations_sequences.automationsequence')),
            ],
            options={
                'ordering': ['email_order'],
            },
        ),
    ]
