# Generated by Django 4.2.23 on 2025-07-26 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailing_automations_sequences', '0001_initial'),
        ('mailing_templates_core', '0001_initial'),
        ('mailing_automations_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequenceemail',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing_templates_core.emailtemplate'),
        ),
        migrations.AddField(
            model_name='automationsequence',
            name='automation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mailing_automations_core.automation'),
        ),
        migrations.AlterUniqueTogether(
            name='sequenceemail',
            unique_together={('sequence', 'email_order')},
        ),
    ]
