# Generated by Django 4.2.23 on 2025-07-26 20:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailing_contacts_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberPreferences',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_marketing', models.BooleanField(default=True)),
                ('email_transactional', models.BooleanField(default=True)),
                ('email_product_updates', models.BooleanField(default=False)),
                ('email_tips_tricks', models.BooleanField(default=False)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('bi_weekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='weekly', max_length=20)),
                ('preferred_send_time', models.TimeField(blank=True, null=True)),
                ('preferred_days', models.JSONField(default=list)),
                ('double_optin_confirmed', models.BooleanField(default=False)),
                ('double_optin_date', models.DateTimeField(blank=True, null=True)),
                ('unsubscribe_reason', models.CharField(blank=True, choices=[('frequency', 'Too frequent'), ('content', 'Content not relevant'), ('cost', 'Too expensive'), ('spam', 'Considered spam'), ('irrelevant', 'Not interested'), ('duplicate', 'Already subscribed elsewhere'), ('other', 'Other reason')], max_length=100)),
                ('gdpr_consent', models.BooleanField(default=False)),
                ('gdpr_consent_date', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('subscriber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mailing_contacts_core.emailsubscriber')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
