# Generated by Django 4.2.23 on 2025-07-26 20:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailing_automations_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationTrigger',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_name', models.CharField(max_length=100)),
                ('trigger_type', models.CharField(choices=[('subscriber_added', 'Subscriber Added'), ('email_opened', 'Email Opened'), ('email_clicked', 'Email Clicked'), ('date_based', 'Date Based'), ('custom_event', 'Custom Event'), ('form_submitted', 'Form Submitted'), ('tag_added', 'Tag Added'), ('list_joined', 'List Joined'), ('purchase_made', 'Purchase Made'), ('website_visit', 'Website Visit')], max_length=30)),
                ('trigger_conditions', models.JSONField(default=dict)),
                ('delay_amount', models.IntegerField(default=0)),
                ('delay_unit', models.CharField(default='minutes', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('trigger_count', models.IntegerField(default=0)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='mailing_automations_core.automation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
