# Generated by Django 4.2.23 on 2025-07-22 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands_core', '0002_initial'),
        ('crm_workflow_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm_workflow_automation', '0001_initial'),
        ('company_categorization_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtrigger',
            name='workflows',
            field=models.ManyToManyField(help_text='Workflows déclenchés', related_name='triggers', through='crm_workflow_automation.TriggerWorkflowAssociation', to='crm_workflow_core.workflow'),
        ),
        migrations.AddField(
            model_name='workflowcondition',
            name='brand',
            field=models.ForeignKey(help_text='Brand gestionnaire de cette entité', on_delete=django.db.models.deletion.CASCADE, to='brands_core.brand'),
        ),
        migrations.AddField(
            model_name='workflowcondition',
            name='company_category',
            field=models.ForeignKey(blank=True, help_text="Secteur d'application du workflow", null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_categorization_core.industrycategory'),
        ),
        migrations.AddField(
            model_name='workflowcondition',
            name='owner',
            field=models.ForeignKey(help_text='Propriétaire/responsable de cette entité', on_delete=django.db.models.deletion.CASCADE, related_name='owned_%(class)s_entities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowaction',
            name='brand',
            field=models.ForeignKey(help_text='Brand gestionnaire de cette entité', on_delete=django.db.models.deletion.CASCADE, to='brands_core.brand'),
        ),
        migrations.AddField(
            model_name='workflowaction',
            name='company_category',
            field=models.ForeignKey(blank=True, help_text="Secteur d'application du workflow", null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_categorization_core.industrycategory'),
        ),
        migrations.AddField(
            model_name='workflowaction',
            name='owner',
            field=models.ForeignKey(help_text='Propriétaire/responsable de cette entité', on_delete=django.db.models.deletion.CASCADE, related_name='owned_%(class)s_entities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='triggerworkflowassociation',
            name='trigger',
            field=models.ForeignKey(help_text='Déclencheur', on_delete=django.db.models.deletion.CASCADE, to='crm_workflow_automation.workflowtrigger'),
        ),
        migrations.AddField(
            model_name='triggerworkflowassociation',
            name='workflow',
            field=models.ForeignKey(help_text='Workflow', on_delete=django.db.models.deletion.CASCADE, to='crm_workflow_core.workflow'),
        ),
        migrations.AddIndex(
            model_name='workflowtrigger',
            index=models.Index(fields=['trigger_type', 'target_object'], name='crm_workflo_trigger_d707ca_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowtrigger',
            index=models.Index(fields=['is_active'], name='crm_workflo_is_acti_9efc08_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowtrigger',
            index=models.Index(fields=['last_triggered_at'], name='crm_workflo_last_tr_c39ff6_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowcondition',
            index=models.Index(fields=['condition_type'], name='crm_workflo_conditi_b141bd_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowcondition',
            index=models.Index(fields=['field_name'], name='crm_workflo_field_n_0c629e_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowcondition',
            index=models.Index(fields=['is_active'], name='crm_workflo_is_acti_98cfe1_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowaction',
            index=models.Index(fields=['action_type'], name='crm_workflo_action__0de30d_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowaction',
            index=models.Index(fields=['is_active'], name='crm_workflo_is_acti_55d173_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='triggerworkflowassociation',
            unique_together={('trigger', 'workflow')},
        ),
    ]
