# Generated by Django 4.2.23 on 2025-07-26 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailing_analytics_clicks', '0001_initial'),
        ('mailing_analytics_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailclick',
            name='email_event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mailing_analytics_core.emailevent'),
        ),
    ]
