# Generated by Django 4.2.23 on 2025-07-26 20:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailing_configuration_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain_name', models.CharField(max_length=255)),
                ('domain_type', models.CharField(choices=[('sending', 'Sending'), ('tracking', 'Tracking'), ('unsubscribe', 'Unsubscribe')], default='sending', max_length=30)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('verification_token', models.CharField(blank=True, max_length=255)),
                ('dns_records', models.JSONField(default=dict)),
                ('ssl_enabled', models.BooleanField(default=False)),
                ('ssl_certificate', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='mailing_configuration_core.mailingaccount')),
            ],
            options={
                'unique_together': {('account', 'domain_name')},
            },
        ),
    ]
