# Generated by Django 4.2.23 on 2025-07-26 20:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailing_contacts_core', '0001_initial'),
        ('mailing_campaigns_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberLifecycle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_stage', models.CharField(choices=[('subscriber', 'Subscriber'), ('lead', 'Lead'), ('qualified_lead', 'Qualified Lead'), ('opportunity', 'Opportunity'), ('customer', 'Customer'), ('advocate', 'Advocate'), ('churned', 'Churned')], default='subscriber', max_length=30)),
                ('previous_stage', models.CharField(blank=True, max_length=30)),
                ('stage_entered_date', models.DateTimeField(auto_now_add=True)),
                ('days_in_current_stage', models.IntegerField(default=0)),
                ('total_stage_changes', models.IntegerField(default=0)),
                ('first_conversion_date', models.DateTimeField(blank=True, null=True)),
                ('last_conversion_date', models.DateTimeField(blank=True, null=True)),
                ('conversion_count', models.IntegerField(default=0)),
                ('attribution_source', models.CharField(blank=True, max_length=100)),
                ('attribution_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing_campaigns_core.campaign')),
                ('subscriber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mailing_contacts_core.emailsubscriber')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
