# Generated by Django 4.2.23 on 2025-07-21 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_core', '0003_company_trial_expires_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text="Nom de la catégorie d'industrie", max_length=100, unique=True)),
                ('category_type', models.CharField(choices=[('fintech', 'Services Financiers & FinTech'), ('saas', 'Software as a Service'), ('realestate', 'Immobilier & Construction'), ('healthcare', 'Santé & Bien-être'), ('ecommerce', 'E-commerce & Retail'), ('services', 'Services Professionnels'), ('manufacturing', 'Industrie & Manufacturing'), ('education', 'Éducation & Formation'), ('media', 'Média & Communication'), ('hospitality', 'Hôtellerie & Tourisme')], help_text='Type de catégorie', max_length=20)),
                ('description', models.TextField(help_text='Description détaillée de la catégorie')),
                ('level', models.IntegerField(default=1, help_text='Niveau hiérarchique (1=principal, 2=sous-catégorie)')),
                ('color_code', models.CharField(default='#6a5acd', help_text="Code couleur hex pour l'affichage", max_length=7)),
                ('icon_name', models.CharField(default='building', help_text="Nom de l'icône (Font Awesome)", max_length=50)),
                ('sort_order', models.IntegerField(default=0, help_text="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, help_text='Catégorie active')),
                ('requires_validation', models.BooleanField(default=False, help_text='Nécessite validation expert pour cette catégorie')),
                ('parent_category', models.ForeignKey(blank=True, help_text='Catégorie parent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='company_categorization_core.industrycategory')),
            ],
            options={
                'verbose_name': 'Catégorie Industrie',
                'verbose_name_plural': 'Catégories Industries',
                'db_table': 'industry_category',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text="Catégorie principale de l'entreprise")),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, help_text='Score de confiance de la catégorisation (0.00-100.00)', max_digits=5, null=True)),
                ('source', models.CharField(choices=[('manual', 'Attribution Manuelle'), ('onboarding', 'Onboarding Utilisateur'), ('ai_detection', 'Détection IA'), ('api_enrichment', 'Enrichissement API'), ('admin_override', 'Override Admin')], default='manual', help_text='Source de la catégorisation', max_length=20)),
                ('is_validated', models.BooleanField(default=False, help_text='Catégorisation validée')),
                ('validated_at', models.DateTimeField(blank=True, help_text='Date de validation', null=True)),
                ('category', models.ForeignKey(help_text='Catégorie assignée', on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='company_categorization_core.industrycategory')),
                ('company', models.ForeignKey(help_text='Entreprise catégorisée', on_delete=django.db.models.deletion.CASCADE, related_name='company_categories', to='company_core.company')),
                ('validated_by', models.ForeignKey(blank=True, help_text='Utilisateur qui a validé', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Catégorie Entreprise',
                'verbose_name_plural': 'Catégories Entreprises',
                'db_table': 'company_category',
                'ordering': ['-is_primary', '-confidence_score'],
            },
        ),
        migrations.AddIndex(
            model_name='industrycategory',
            index=models.Index(fields=['category_type'], name='industry_ca_categor_c6002a_idx'),
        ),
        migrations.AddIndex(
            model_name='industrycategory',
            index=models.Index(fields=['is_active'], name='industry_ca_is_acti_339cee_idx'),
        ),
        migrations.AddIndex(
            model_name='industrycategory',
            index=models.Index(fields=['parent_category', 'level'], name='industry_ca_parent__3cbb7e_idx'),
        ),
        migrations.AddIndex(
            model_name='companycategory',
            index=models.Index(fields=['company', 'is_primary'], name='company_cat_company_3f8732_idx'),
        ),
        migrations.AddIndex(
            model_name='companycategory',
            index=models.Index(fields=['category', 'is_validated'], name='company_cat_categor_1dd2f5_idx'),
        ),
        migrations.AddIndex(
            model_name='companycategory',
            index=models.Index(fields=['source'], name='company_cat_source_650024_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='companycategory',
            unique_together={('company', 'category')},
        ),
    ]
