# Generated by Django 4.2.23 on 2025-07-26 20:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConversion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversion_type', models.CharField(choices=[('purchase', 'Purchase'), ('signup', 'Signup'), ('download', 'Download'), ('demo_request', 'Demo Request'), ('trial_start', 'Trial Start'), ('form_submit', 'Form Submit'), ('page_visit', 'Page Visit'), ('custom', 'Custom')], max_length=30)),
                ('conversion_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('CHF', 'Swiss Franc'), ('JPY', 'Japanese Yen')], default='EUR', max_length=3)),
                ('conversion_url', models.URLField(blank=True)),
                ('attribution_window_hours', models.IntegerField(default=24)),
                ('time_to_conversion_minutes', models.IntegerField(default=0)),
                ('conversion_metadata', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
