# Generated by Django 4.2.23 on 2025-07-21 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_core', '0003_company_trial_expires_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesCompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('additional_info', models.JSONField(blank=True, default=dict, help_text='Informations additionnelles spécifiques au secteur')),
                ('industry_score', models.IntegerField(blank=True, help_text="Score d'adéquation avec le secteur (0-100)", null=True)),
                ('is_validated', models.BooleanField(default=False, help_text='Profil validé par un expert secteur')),
                ('validated_at', models.DateTimeField(blank=True, help_text='Date de validation', null=True)),
                ('service_type', models.CharField(choices=[('consulting', 'Conseil & Stratégie'), ('legal', 'Services Juridiques'), ('accounting', 'Comptabilité & Audit'), ('marketing', 'Marketing & Communication'), ('it_services', 'Services IT & Digital'), ('hr_services', 'RH & Recrutement'), ('training', 'Formation & Développement'), ('design', 'Design & Créatif'), ('architecture', 'Architecture & Ingénierie'), ('maintenance', 'Maintenance & Support'), ('logistics', 'Logistique & Transport'), ('security', 'Sécurité & Surveillance')], help_text='Type de service principal', max_length=20)),
                ('delivery_model', models.CharField(choices=[('on_premise', 'Sur Site Client'), ('remote', 'À Distance'), ('hybrid', 'Hybride'), ('office_based', 'En Agence')], help_text='Modèle de prestation', max_length=15)),
                ('specialization', models.CharField(blank=True, help_text='Spécialisation ou niche', max_length=100)),
                ('target_industries', models.TextField(blank=True, help_text='Secteurs clients cibles')),
                ('consultants_count', models.IntegerField(blank=True, help_text='Nombre de consultants/experts', null=True)),
                ('partners_count', models.IntegerField(blank=True, help_text="Nombre d'associés", null=True)),
                ('professional_certifications', models.TextField(blank=True, help_text='Certifications professionnelles (ISO, PMP, etc.)')),
                ('industry_memberships', models.TextField(blank=True, help_text='Adhésions organisations professionnelles')),
                ('hourly_rate_range', models.CharField(blank=True, help_text='Fourchette tarif horaire (€)', max_length=50)),
                ('project_size_range', models.CharField(blank=True, help_text='Fourchette taille projets (€)', max_length=50)),
                ('client_retention_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Taux de rétention clients (%)', max_digits=5, null=True)),
                ('serves_sme', models.BooleanField(default=True, help_text='Sert les PME')),
                ('serves_large_corps', models.BooleanField(default=False, help_text='Sert les grandes entreprises')),
                ('serves_public_sector', models.BooleanField(default=False, help_text='Sert le secteur public')),
                ('methodologies_used', models.TextField(blank=True, help_text='Méthodologies utilisées (Agile, Lean, Six Sigma)')),
                ('uses_project_mgmt_tools', models.BooleanField(default=False, help_text='Utilise des outils de gestion de projets')),
                ('offers_digital_deliverables', models.BooleanField(default=False, help_text='Livre des résultats digitaux')),
                ('has_proprietary_tools', models.BooleanField(default=False, help_text="Dispose d'outils propriétaires")),
                ('notable_clients', models.TextField(blank=True, help_text='Clients notables (si public)')),
                ('case_studies_count', models.IntegerField(blank=True, help_text="Nombre d'études de cas documentées", null=True)),
                ('company', models.OneToOneField(help_text='Entreprise associée à ce profil', on_delete=django.db.models.deletion.CASCADE, to='company_core.company')),
                ('validated_by', models.ForeignKey(blank=True, help_text='Expert qui a validé le profil', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Services',
                'verbose_name_plural': 'Profils Services',
                'db_table': 'services_company_profile',
                'indexes': [models.Index(fields=['service_type'], name='services_co_service_9c21d3_idx'), models.Index(fields=['delivery_model'], name='services_co_deliver_f45b23_idx'), models.Index(fields=['serves_large_corps'], name='services_co_serves__911f68_idx')],
            },
        ),
    ]
